---
Name: modelascontrollerroutes
After: cms/routes#modelascontrollerroutes
---
Director:
    rules:
        '': 'PrefixModelAsController'
        '$URLSegment//$Action/$ID/$OtherID': 'PrefixModelAsController'
